adding first style on the homepage
WildCodeSchool/2022-09-JS-Reims-project-2-lalambic pull request #15
Opened 2022-10-26 12:47 UTC by Louen52

2022-10-26 15:20 UTC, Justine-Merlin requested changes

2022-10-26 15:20 UTC, Justine-Merlin commented on frontend/src/components/Lang.css
> +
Delete blank line.

2022-10-26 15:20 UTC, Justine-Merlin commented on frontend/src/components/Lang.css
> +* {
Style apply to * has to be in global file like app.css.

2022-10-26 15:20 UTC, Justine-Merlin commented on frontend/src/components/SearchBar.css
> +* {
Same here.

2022-10-26 15:20 UTC, Justine-Merlin commented on frontend/src/components/SearchBar.css
> +    padding:0.8rem;
You have multiple "padding" properties (padding-left, padding, padding-left again and padding-rigth). Choose what padding you want and set it in one property "padding". Look at padding property in MDN if needed.

2022-10-26 15:20 UTC, Justine-Merlin commented on frontend/src/components/SearchBar.css
> +    outline: none;
Don't hide outline because of accessibility.

2022-10-26 15:20 UTC, Justine-Merlin commented on frontend/src/components/section.css
>  * {
Same here.

2022-10-26 15:20 UTC, Justine-Merlin commented on frontend/src/components/section.css
>  * {
File might be call Section.css to fit other css files convention syntax

2022-10-28 07:13 UTC, rocambille commented on frontend/src/components/Lang.css
> +* {
still waiting for correction

2022-10-28 07:13 UTC, rocambille commented
conflicts to resolve

2022-10-28 07:52 UTC, merged